In [4]:
# 1.Create a function to check whether numpy array has Zero values or not.
import numpy as np

arr = np.array([int(x) for x in input("Enter elements of the array separated by space: ").strip().split()])
zero_positions = np.where(arr == 0)[0]
if zero_positions.size > 0:
    print(f"Zero values present at positions: {zero_positions.tolist()}")
else:
    print("No zero values present")

Enter elements of the array separated by space: 0
Zero values present at positions: [0]


In [9]:
# 2.Consider an array contains marks of students. Find the median and mean of students who got passing marks.
import numpy as np

arr = np.array([int(x) for x in input("Enter marks of students separated by space: ").strip().split()])

passing_marks = arr[arr >= 40]

if passing_marks.size > 0:
    median_marks = np.median(passing_marks)
    mean_marks = np.mean(passing_marks)
    print(f"Median of passing marks: {median_marks}")
    print(f"Mean of passing marks: {mean_marks}")
else:
    print("No students with passing marks.")

Enter marks of students separated by space: 45 50 10 12
Median of passing marks: 47.5
Mean of passing marks: 47.5


In [10]:
# 3.Consider an array containing date of birth of students (Use np.datetime64('2018-02-01')). Find the age of all students. If age is 18 label it First, if it is 19, label it Second, if it is 20, label it Third, if it is 21, label it Fourth.
import numpy as np
from datetime import datetime

dob_array = np.array([
    np.datetime64('2005-02-01'),
    np.datetime64('2004-06-15'),
    np.datetime64('2003-09-10'),
    np.datetime64('2002-12-05')
])

current_date = np.datetime64(datetime.now().date())

ages = (current_date - dob_array).astype('timedelta64[Y]').astype(int)

labels = []
for age in ages:
    if age == 18:
        labels.append("First")
    elif age == 19:
        labels.append("Second")
    elif age == 20:
        labels.append("Third")
    elif age == 21:
        labels.append("Fourth")
    else:
        labels.append("No Label")

for dob, age, label in zip(dob_array, ages, labels):
    print(f"DOB: {dob}, Age: {age}, Label: {label}")

DOB: 2005-02-01, Age: 20, Label: Third
DOB: 2004-06-15, Age: 20, Label: Third
DOB: 2003-09-10, Age: 21, Label: Fourth
DOB: 2002-12-05, Age: 22, Label: No Label


In [23]:
# 4. Create a function to sort 2d Array by a column.

import numpy as np

arr = np.random.randint(1, 10, size=(3, 3))
sorted_arr = np.sort(arr, axis=0)

print("Original Array:")
print(arr)
print("\nSorted Array:")
print(sorted_arr)


Original Array:
[[9 5 7]
 [3 7 3]
 [1 5 1]]

Sorted Array:
[[1 5 1]
 [3 5 3]
 [9 7 7]]
