KNeighborsClassifier(3),     SVC(kernel="linear", C=0.025),     SVC(gamma=2, C=1),     GaussianProcessClassifier(1.0 * RBF(1.0)),     DecisionTreeClassifier(max_depth=5),     RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),     MLPClassifier(alpha=1),     AdaBoostClassifier(),     GaussianNB(),     QuadraticDiscriminantAnalysis()

In [ ]:
import random
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [ ]:
iris=datasets.load_iris()
digits=datasets.load_digits()
x,y=iris.data,iris.target
x=np.array(x)
y=np.array(y)

boston=pd.read_csv("HousingData.csv")
boston.dropna(inplace=True)
boston=boston.astype(float)
boston['PRICE_CAT']=(boston['MEDV']>boston['MEDV'].median()).astype(int)
boston=boston.apply(pd.to_numeric,errors='coerce')

print("IRIS DATASET")
print(iris.DESCR)
print("\n DIGITS DATASET")
print(digits.DESCR)
print("\n BOSTON HOUSING DATASET")
print(boston.head(10))

IRIS DATASET
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3

In [ ]:
print(iris.keys())
print("Header : ", iris.feature_names)
print("Target : ", iris.target[np.random.choice(150,20)])
print(iris.data.shape)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
Header :  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target :  [1 2 2 2 2 1 2 2 1 2 0 2 1 1 0 0 1 0 0 0]
(150, 4)


In [ ]:
print(digits.keys())
print("Header : ", digits.feature_names)
print("Target : ", digits.target[np.random.choice(150,20)])
print(digits.data.shape)

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])
Header :  ['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1', 'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6', 'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3', 'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'pixel_7_7']
Target :  [8 5 3 6 2 5 8 4 7 8 1 2 9 7 6 8 2 8 6 9]
(1797, 64)


In [ ]:
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)
XDigits_train, XDigits_test, yDigits_train, yDigits_test = train_test_split(digits.data, digits.target, test_size=0.4, random_state=4)
XBoston = boston.drop(['MEDV', 'PRICE_CAT'], axis=1)
yBoston = boston['PRICE_CAT']
XBoston_train, XBoston_test, yBoston_train, yBoston_test = train_test_split(XBoston, yBoston, test_size=0.2, random_state=4)

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)
knnBoston=KNeighborsClassifier(n_neighbors=3)
knnDigits=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
knnBoston.fit(XBoston_train, yBoston_train)
knnDigits.fit(XDigits_train, yDigits_train)
y_pred=knn.predict(X_test)
yBoston_pred=knnBoston.predict(XBoston_test)
yDigits_pred=knnDigits.predict(XDigits_test)
print(f'Boston:{metrics.mean_squared_error(yBoston_test, yBoston_pred)}')
print(f'Iris:{metrics.accuracy_score(y_test, y_pred)}')
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))
print(f'Iris:{metrics.accuracy_score(y_test, y_pred)}')
print(metrics.confusion_matrix(yBoston_test, yBoston_pred))
print(metrics.classification_report(yBoston_test, yBoston_pred))
print(f'Digits:{metrics.accuracy_score(yDigits_test, yDigits_pred)}')
print(metrics.confusion_matrix(yDigits_test, yDigits_pred))
print(metrics.classification_report(yDigits_test, yDigits_pred))

Boston:0.13924050632911392
Iris:0.9666666666666667
[[16  0  0]
 [ 0  4  1]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.80      0.89         5
           2       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.93      0.95        30
weighted avg       0.97      0.97      0.97        30

Iris:0.9666666666666667
[[34  4]
 [ 7 34]]
              precision    recall  f1-score   support

           0       0.83      0.89      0.86        38
           1       0.89      0.83      0.86        41

    accuracy                           0.86        79
   macro avg       0.86      0.86      0.86        79
weighted avg       0.86      0.86      0.86        79

Digits:0.9833101529902643
[[77  0  0  0  0  0  0  0  0  0]
 [ 0 69  0  0  0  0  0  0  0  0]
 [ 0  0 71  0  0  0  0  1  0  0]
 [ 0  0  0 77  0  1  0  0  0  0]
 [ 

In [ ]:
svc_model = svm.SVC( C=0.025, kernel='linear')
svc_model.fit(X_train, y_train)
svc_pred=svc_model.predict(X_test)
print(metrics.accuracy_score(y_test, svc_pred))
print(metrics.confusion_matrix(y_test, svc_pred))
print(metrics.classification_report(y_test, svc_pred))
svcModelDigits=svm.SVC( C=0.025, kernel='linear')
svcModelDigits.fit(XDigits_train, yDigits_train)
svcModelDigitsPred=svcModelDigits.predict(XDigits_test)
print(metrics.accuracy_score(yDigits_test, svcModelDigitsPred))
print(metrics.confusion_matrix(yDigits_test, svcModelDigitsPred))
print(metrics.classification_report(yDigits_test, svcModelDigitsPred))
svcModelBoston=svm.SVC( C=0.025, kernel='linear')
svcModelBoston.fit(XBoston_train, yBoston_train)
svcModelBostonPred=svcModelBoston.predict(XBoston_test)
print(metrics.accuracy_score(yBoston_test, svcModelBostonPred))
print(metrics.confusion_matrix(yBoston_test, svcModelBostonPred))
print(metrics.classification_report(yBoston_test, svcModelBostonPred))

0.9666666666666667
[[16  0  0]
 [ 0  4  1]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.80      0.89         5
           2       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.93      0.95        30
weighted avg       0.97      0.97      0.97        30

0.9777468706536857
[[77  0  0  0  0  0  0  0  0  0]
 [ 0 69  0  0  0  0  0  0  0  0]
 [ 0  0 72  0  0  0  0  0  0  0]
 [ 0  1  0 75  0  0  0  0  0  2]
 [ 0  2  0  0 65  0  0  0  0  0]
 [ 0  0  0  0  0 70  0  0  0  1]
 [ 0  0  0  0  0  0 75  0  1  0]
 [ 0  0  0  0  0  0  0 70  1  0]
 [ 0  3  0  0  0  0  0  0 64  0]
 [ 0  1  0  0  0  0  0  0  4 66]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        77
           1       0.91      1.00      0.95        69
           2       1.00      1.00      1.00       

In [ ]:
svcModel2=svm.SVC(gamma=2, C=1)
svcModel2.fit(X_train, y_train)
svc2Pred=svcModel2.predict(X_test)
print(metrics.accuracy_score(y_test, svc2Pred))
print(metrics.confusion_matrix(y_test, svc2Pred))
print(metrics.classification_report(y_test, svc2Pred))
digitsSvcModel=svm.SVC(gamma=2,C=1)
digitsSvcModel.fit(XDigits_train, yDigits_train)
svcModel2Pred=digitsSvcModel.predict(XDigits_test)
print(metrics.accuracy_score(yDigits_test, svcModel2Pred))
print(metrics.confusion_matrix(yDigits_test, svcModel2Pred))
print(metrics.classification_report(yDigits_test, svcModel2Pred))
BostonSvcModel=svm.SVC(gamma=2,C=1)
BostonSvcModel.fit(XBoston_train, yBoston_train)
svcModel2Pred=BostonSvcModel.predict(XBoston_test)
print(metrics.accuracy_score(yBoston_test, svcModel2Pred))
print(metrics.confusion_matrix(yBoston_test, svcModel2Pred))
print(metrics.classification_report(yBoston_test, svcModel2Pred))

0.9666666666666667
[[16  0  0]
 [ 0  4  1]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.80      0.89         5
           2       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.93      0.95        30
weighted avg       0.97      0.97      0.97        30

0.09318497913769123
[[ 0  0  0  0 77  0  0  0  0  0]
 [ 0  0  0  0 69  0  0  0  0  0]
 [ 0  0  0  0 72  0  0  0  0  0]
 [ 0  0  0  0 78  0  0  0  0  0]
 [ 0  0  0  0 67  0  0  0  0  0]
 [ 0  0  0  0 71  0  0  0  0  0]
 [ 0  0  0  0 76  0  0  0  0  0]
 [ 0  0  0  0 71  0  0  0  0  0]
 [ 0  0  0  0 67  0  0  0  0  0]
 [ 0  0  0  0 71  0  0  0  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        77
           1       0.00      0.00      0.00        69
           2       0.00      0.00      0.00      

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
gpc = GaussianProcessClassifier(kernel=1.0*RBF(1.0),random_state=0)
gpc.fit(X_train, y_train)
gpcPred=gpc.predict(X_test)
print(metrics.accuracy_score(y_test, gpcPred))
print(metrics.confusion_matrix(y_test, gpcPred))
print(metrics.classification_report(y_test, gpcPred))
gpcDigits=GaussianProcessClassifier(kernel=1.0*RBF(1.0),random_state=0)
gpcDigits.fit(XDigits_train, yDigits_train)
gpcDigitsPred=gpcDigits.predict(XDigits_test)
print(metrics.accuracy_score(yDigits_test, gpcDigitsPred))
print(metrics.confusion_matrix(yDigits_test, gpcDigitsPred))
print(metrics.classification_report(yDigits_test, gpcDigitsPred))
gpcBoston=GaussianProcessClassifier(kernel=1.0*RBF(1.0),random_state=0)
gpcBoston.fit(XBoston_train, yBoston_train)
gpcBostonPred=gpcBoston.predict(XBoston_test)
print(metrics.accuracy_score(yBoston_test, gpcBostonPred))
print(metrics.confusion_matrix(yBoston_test, gpcBostonPred))
print(metrics.classification_report(yBoston_test, gpcBostonPred))

0.9333333333333333
[[16  0  0]
 [ 0  4  1]
 [ 0  1  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.80      0.80      0.80         5
           2       0.89      0.89      0.89         9

    accuracy                           0.93        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.93      0.93      0.93        30

0.09874826147426982
[[ 0  0  0  0  0  0  0  0  0 77]
 [ 0  0  0  0  0  0  0  0  0 69]
 [ 0  0  0  0  0  0  0  0  0 72]
 [ 0  0  0  0  0  0  0  0  0 78]
 [ 0  0  0  0  0  0  0  0  0 67]
 [ 0  0  0  0  0  0  0  0  0 71]
 [ 0  0  0  0  0  0  0  0  0 76]
 [ 0  0  0  0  0  0  0  0  0 71]
 [ 0  0  0  0  0  0  0  0  0 67]
 [ 0  0  0  0  0  0  0  0  0 71]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        77
           1       0.00      0.00      0.00        69
           2       0.00      0.00      0.00      

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


0.8607594936708861
[[32  6]
 [ 5 36]]
              precision    recall  f1-score   support

           0       0.86      0.84      0.85        38
           1       0.86      0.88      0.87        41

    accuracy                           0.86        79
   macro avg       0.86      0.86      0.86        79
weighted avg       0.86      0.86      0.86        79



/usr/local/lib/python3.11/dist-packages/sklearn/gaussian_process/kernels.py:452: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__constant_value is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(


Mean Absolute Error (MAE): 3.142198642813668
Root Mean Squared Error (RMSE): 4.417889558557826


In [ ]:
decisionTree=DecisionTreeClassifier(max_depth=5)
decisionTree.fit(X_train, y_train)
decisionTreePred=decisionTree.predict(X_test)
print(metrics.accuracy_score(y_test, decisionTreePred))
print(metrics.confusion_matrix(y_test, decisionTreePred))
print(metrics.classification_report(y_test, decisionTreePred))
decisionTreeDigits=DecisionTreeClassifier(max_depth=5)
decisionTreeDigits.fit(XDigits_train, yDigits_train)
decisionTreeDigitsPred=decisionTreeDigits.predict(XDigits_test)
print(metrics.accuracy_score(yDigits_test, decisionTreeDigitsPred))
print(metrics.confusion_matrix(yDigits_test, decisionTreeDigitsPred))
print(metrics.classification_report(yDigits_test, decisionTreeDigitsPred))
decisionTreeBoston=DecisionTreeClassifier(max_depth=5)
decisionTreeBoston.fit(XBoston_train, yBoston_train)
decisionTreeBostonPred=decisionTreeBoston.predict(XBoston_test)
print(metrics.accuracy_score(yBoston_test, decisionTreeBostonPred))
print(metrics.confusion_matrix(yBoston_test, decisionTreeBostonPred))
print(metrics.classification_report(yBoston_test, decisionTreeBostonPred))

0.9666666666666667
[[16  0  0]
 [ 0  4  1]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.80      0.89         5
           2       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.93      0.95        30
weighted avg       0.97      0.97      0.97        30

0.6606397774687065
[[73  0  0  1  0  0  0  0  1  2]
 [ 0 16  6  4  0  1  0  2 40  0]
 [ 0  1 19  3  1  1  0  0 47  0]
 [ 0  3  8 60  0  0  0  1  6  0]
 [ 0  8  0  1 52  1  0  0  5  0]
 [ 0  0  2  2  1 65  0  1  0  0]
 [ 1  8  0  0  1  1 65  0  0  0]
 [ 0  4  0  0  3  0  0 61  3  0]
 [ 0  0  3  8  0  1  0  2 51  2]
 [ 0  0  2 46  1  3  1  2  3 13]]
              precision    recall  f1-score   support

           0       0.99      0.95      0.97        77
           1       0.40      0.23      0.29        69
           2       0.47      0.26      0.34       

In [ ]:
randomForest=RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1)
randomForest.fit(X_train, y_train)
randomForestPred=randomForest.predict(X_test)
print(metrics.accuracy_score(y_test, randomForestPred))
print(metrics.confusion_matrix(y_test, randomForestPred))
print(metrics.classification_report(y_test, randomForestPred))
randomForestDigits=RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1)
randomForestDigits.fit(XDigits_train, yDigits_train)
randomForestDigitsPred=randomForestDigits.predict(XDigits_test)
print(metrics.accuracy_score(yDigits_test, randomForestDigitsPred))
print(metrics.confusion_matrix(yDigits_test, randomForestDigitsPred))
print(metrics.classification_report(yDigits_test, randomForestDigitsPred))
randomForestBoston=RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1)
randomForestBoston.fit(XBoston_train, yBoston_train)
randomForestBostonPred=randomForestBoston.predict(XBoston_test)
print(metrics.accuracy_score(yBoston_test, randomForestBostonPred))
print(metrics.confusion_matrix(yBoston_test, randomForestBostonPred))
print(metrics.classification_report(yBoston_test, randomForestBostonPred))

0.9333333333333333
[[16  0  0]
 [ 0  4  1]
 [ 0  1  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.80      0.80      0.80         5
           2       0.89      0.89      0.89         9

    accuracy                           0.93        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.93      0.93      0.93        30

0.8108484005563282
[[75  0  0  0  0  0  1  0  0  1]
 [ 0 52  6  0  6  4  1  0  0  0]
 [ 1  4 64  0  0  1  0  1  1  0]
 [ 0  2  4 58  0  4  4  0  4  2]
 [ 2  2  0  0 61  1  0  1  0  0]
 [ 1  0  0  2  1 65  0  1  1  0]
 [ 0  4  0  0  0  2 70  0  0  0]
 [ 0  0  0  0  4  1  0 66  0  0]
 [ 3 10  2  3  1  1  1  4 30 12]
 [ 1  2  0  9  9  2  1  2  3 42]]
              precision    recall  f1-score   support

           0       0.90      0.97      0.94        77
           1       0.68      0.75      0.72        69
           2       0.84      0.89      0.86       

In [ ]:
mlpClassifier=MLPClassifier(alpha=1)
mlpClassifier.fit(X_train, y_train)
mlpClassifierPred=mlpClassifier.predict(X_test)
print(metrics.accuracy_score(y_test, mlpClassifierPred))
print(metrics.confusion_matrix(y_test, mlpClassifierPred))
print(metrics.classification_report(y_test, mlpClassifierPred))
mlpClassifierDigits=MLPClassifier(alpha=1)
mlpClassifierDigits.fit(XDigits_train, yDigits_train)
mlpClassifierDigitsPred=mlpClassifierDigits.predict(XDigits_test)
print(metrics.accuracy_score(yDigits_test, mlpClassifierDigitsPred))
print(metrics.confusion_matrix(yDigits_test, mlpClassifierDigitsPred))
print(metrics.classification_report(yDigits_test, mlpClassifierDigitsPred))
mlpClassifierBoston=MLPClassifier(alpha=1)
mlpClassifierBoston.fit(XBoston_train, yBoston_train)
mlpClassifierBostonPred=mlpClassifierBoston.predict(XBoston_test)
print(metrics.accuracy_score(yBoston_test, mlpClassifierBostonPred))
print(metrics.confusion_matrix(yBoston_test, mlpClassifierBostonPred))
print(metrics.classification_report(yBoston_test, mlpClassifierBostonPred))

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


0.9666666666666667
[[16  0  0]
 [ 0  4  1]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.80      0.89         5
           2       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.93      0.95        30
weighted avg       0.97      0.97      0.97        30



/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


0.9707927677329624
[[77  0  0  0  0  0  0  0  0  0]
 [ 0 68  0  1  0  0  0  0  0  0]
 [ 0  0 71  0  0  0  0  1  0  0]
 [ 0  0  0 72  0  2  0  0  2  2]
 [ 0  1  0  0 66  0  0  0  0  0]
 [ 0  1  0  0  0 68  0  0  0  2]
 [ 0  0  0  0  0  0 76  0  0  0]
 [ 0  0  0  0  0  0  0 71  0  0]
 [ 0  3  0  0  0  0  0  0 64  0]
 [ 0  2  0  0  0  0  0  0  4 65]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        77
           1       0.91      0.99      0.94        69
           2       1.00      0.99      0.99        72
           3       0.99      0.92      0.95        78
           4       1.00      0.99      0.99        67
           5       0.97      0.96      0.96        71
           6       1.00      1.00      1.00        76
           7       0.99      1.00      0.99        71
           8       0.91      0.96      0.93        67
           9       0.94      0.92      0.93        71

    accuracy                           0.97       719


In [ ]:
adaBoost=AdaBoostClassifier()
adaBoost.fit(X_train, y_train)
adaBoostPred=adaBoost.predict(X_test)
print(metrics.accuracy_score(y_test, adaBoostPred))
print(metrics.confusion_matrix(y_test, adaBoostPred))
print(metrics.classification_report(y_test, adaBoostPred))
adaBoostDigits=AdaBoostClassifier()
adaBoostDigits.fit(XDigits_train, yDigits_train)
adaBoostDigitsPred=adaBoostDigits.predict(XDigits_test)
print(metrics.accuracy_score(yDigits_test, adaBoostDigitsPred))
print(metrics.confusion_matrix(yDigits_test, adaBoostDigitsPred))
print(metrics.classification_report(yDigits_test, adaBoostDigitsPred))
adaBoostBoston=AdaBoostClassifier()
adaBoostBoston.fit(XBoston_train, yBoston_train)
adaBoostBostonPred=adaBoostBoston.predict(XBoston_test)
print(metrics.accuracy_score(yBoston_test, adaBoostBostonPred))
print(metrics.confusion_matrix(yBoston_test, adaBoostBostonPred))
print(metrics.classification_report(yBoston_test, adaBoostBostonPred))

0.9666666666666667
[[16  0  0]
 [ 0  4  1]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.80      0.89         5
           2       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.93      0.95        30
weighted avg       0.97      0.97      0.97        30

0.7677329624478443
[[69  0  0  0  2  0  1  1  2  2]
 [ 0 38  8  6  3  0  0  3  8  3]
 [ 0  0 37  8  0  1  5  0 20  1]
 [ 0  2  2 63  0  6  1  0  2  2]
 [ 2  2  0  0 61  0  0  1  1  0]
 [ 2  0  0  0  6 58  0  2  0  3]
 [ 1  6  0  0  2  0 67  0  0  0]
 [ 0  0  0  3  3  0  0 53 10  2]
 [ 0  2  6  3  0  1  0  0 55  0]
 [ 0  2  4  7  2  1  0  2  2 51]]
              precision    recall  f1-score   support

           0       0.93      0.90      0.91        77
           1       0.73      0.55      0.63        69
           2       0.65      0.51      0.57       

In [ ]:
gaussianNb=GaussianNB()
gaussianNb.fit(X_train, y_train)
gaussianNbPred=gaussianNb.predict(X_test)
print(metrics.accuracy_score(y_test, gaussianNbPred))
print(metrics.confusion_matrix(y_test, gaussianNbPred))
print(metrics.classification_report(y_test, gaussianNbPred))
gaussianNbDigits=GaussianNB()
gaussianNbDigits.fit(XDigits_train, yDigits_train)
gaussianNbDigitsPred=gaussianNbDigits.predict(XDigits_test)
print(metrics.accuracy_score(yDigits_test, gaussianNbDigitsPred))
print(metrics.confusion_matrix(yDigits_test, gaussianNbDigitsPred))
print(metrics.classification_report(yDigits_test, gaussianNbDigitsPred))
gaussianNbBoston=GaussianNB()
gaussianNbBoston.fit(XBoston_train, yBoston_train)
gaussianNbBostonPred=gaussianNbBoston.predict(XBoston_test)
print(metrics.accuracy_score(yBoston_test, gaussianNbBostonPred))
print(metrics.confusion_matrix(yBoston_test, gaussianNbBostonPred))
print(metrics.classification_report(yBoston_test, gaussianNbBostonPred))

0.9666666666666667
[[16  0  0]
 [ 0  5  0]
 [ 0  1  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.83      1.00      0.91         5
           2       1.00      0.89      0.94         9

    accuracy                           0.97        30
   macro avg       0.94      0.96      0.95        30
weighted avg       0.97      0.97      0.97        30

0.8692628650904033
[[76  0  0  0  1  0  0  0  0  0]
 [ 0 45  8  0  0  0  2  3  7  4]
 [ 0  3 62  0  1  0  0  0  6  0]
 [ 0  0  1 64  0  2  1  1  9  0]
 [ 0  1  0  0 61  0  2  2  1  0]
 [ 0  0  0  0  0 65  3  1  1  1]
 [ 0  0  1  0  1  1 73  0  0  0]
 [ 0  0  1  0  0  1  0 68  1  0]
 [ 0  2  0  1  0  0  0  1 63  0]
 [ 0  5  1  2  0  0  0  7  8 48]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99        77
           1       0.80      0.65      0.72        69
           2       0.84      0.86      0.85       

In [ ]:
QDM=QuadraticDiscriminantAnalysis()
QDM.fit(X_train, y_train)
QDMPred=QDM.predict(X_test)
print(metrics.accuracy_score(y_test, QDMPred))
print(metrics.confusion_matrix(y_test, QDMPred))
print(metrics.classification_report(y_test, QDMPred))
QDMDigits=QuadraticDiscriminantAnalysis()
QDMDigits.fit(XDigits_train, yDigits_train)
QDMDigitsPred=QDMDigits.predict(XDigits_test)
print(metrics.accuracy_score(yDigits_test, QDMDigitsPred))
print(metrics.confusion_matrix(yDigits_test, QDMDigitsPred))
print(metrics.classification_report(yDigits_test, QDMDigitsPred))
QDMBoston=QuadraticDiscriminantAnalysis()
QDMBoston.fit(XBoston_train, yBoston_train)
QDMBostonPred=QDMBoston.predict(XBoston_test)
print(metrics.accuracy_score(yBoston_test, QDMBostonPred))
print(metrics.confusion_matrix(yBoston_test, QDMBostonPred))
print(metrics.classification_report(yBoston_test, QDMBostonPred))

0.9
[[16  0  0]
 [ 0  3  2]
 [ 0  1  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.75      0.60      0.67         5
           2       0.80      0.89      0.84         9

    accuracy                           0.90        30
   macro avg       0.85      0.83      0.84        30
weighted avg       0.90      0.90      0.90        30

0.8595271210013908
[[76  0  0  0  1  0  0  0  0  0]
 [ 0 66  0  0  0  0  1  1  1  0]
 [ 0  4 62  0  1  0  0  0  5  0]
 [ 0  1  1 24  0  3  2  1 30 16]
 [ 0  1  0  0 59  0  1  6  0  0]
 [ 0  0  0  0  0 69  0  0  1  1]
 [ 0  0  0  0  0  1 74  0  1  0]
 [ 0  0  0  0  0  1  0 69  1  0]
 [ 0  2  0  0  0  1  0  1 63  0]
 [ 0  1  1  0  1  0  0  4  8 56]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99        77
           1       0.88      0.96      0.92        69
           2       0.97      0.86      0.91        72
           

/usr/local/lib/python3.11/dist-packages/sklearn/discriminant_analysis.py:1024: LinAlgWarning: The covariance matrix of class 0 is not full rank. Increasing the value of parameter `reg_param` might help reducing the collinearity.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/discriminant_analysis.py:1024: LinAlgWarning: The covariance matrix of class 1 is not full rank. Increasing the value of parameter `reg_param` might help reducing the collinearity.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/discriminant_analysis.py:1024: LinAlgWarning: The covariance matrix of class 2 is not full rank. Increasing the value of parameter `reg_param` might help reducing the collinearity.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/discriminant_analysis.py:1024: LinAlgWarning: The covariance matrix of class 3 is not full rank. Increasing the value of parameter `reg_param` might help reducing the collinearity.
  warnings.warn(
/usr/local/lib/p