1.Create one hot encoding of an array.

In [1]:
import numpy as np

arr = input("Enter integers separated by spaces: ").split()
arr = [int(x) for x in arr]

unique_classes = np.unique(arr)
encoded_array = np.zeros((len(arr), len(unique_classes)))

for i in range(len(arr)):
    encoded_array[i, np.where(unique_classes == arr[i])] = 1

print("One Hot Encoded Array:\n", encoded_array)


Enter integers separated by spaces: 2 3  2 2 2 1
One Hot Encoded Array:
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


2.Drop all missing values from an array Input: np.array([1,2,3,np.nan,5,6,7,np.nan]) Desired Output: array([ 1.,2.,3.,5.,6.,7.])

In [3]:
import numpy as np

arr = input("Enter values separated by spaces (NaN for missing): ").split()
arr = [float(x) if x.lower() != 'nan' else np.nan for x in arr]

arr = np.array(arr)
cleaned_array = arr[~np.isnan(arr)]

print("Cleaned Array:", cleaned_array)


Enter values separated by spaces (NaN for missing): 1 2 3 NaN 5 6 7 NaN
Cleaned Array: [1. 2. 3. 5. 6. 7.]


3.Find Index of Local maxima from an array. Input: a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) Desired Output: array([2, 5])

In [4]:
import numpy as np

arr = input("Enter integers separated by spaces: ").split()
arr = np.array([int(x) for x in arr])

local_maxima_indices = np.where((arr[1:-1] > arr[:-2]) & (arr[1:-1] > arr[2:]))[0] + 1

print("Indices of Local Maxima:", local_maxima_indices)


Enter integers separated by spaces: 1 3 7 1 2 6 0 1
Indices of Local Maxima: [2 5]


4.From the given 1d array arr, generate a 2d matrix using strides,
For example for an array ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])with a window length of w=4 and strides of s=2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]
w and s will be provided by user
Calculate the moving average.

In [5]:
import numpy as np

def generate_stride_matrix_and_moving_average(arr, window_length, stride):
    print(f"\nInput Array: {arr}")

    shape = ((len(arr) - window_length) // stride + 1, window_length)
    strides = (arr.strides[0] * stride, arr.strides[0])
    strided_matrix = np.lib.stride_tricks.as_strided(arr, shape=shape, strides=strides)

    print("\nGenerated Strided Matrix:")
    print(strided_matrix)

    moving_averages = np.mean(strided_matrix, axis=1)

    print("\nMoving Averages:")
    print(moving_averages)

arr = list(map(int, input("Enter the array elements separated by space: ").split()))
arr = np.array(arr)
window_length = int(input("Enter window length: "))
stride = int(input("Enter stride value: "))

generate_stride_matrix_and_moving_average(arr, window_length, stride)


Enter the array elements separated by space: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14
Enter window length: 4
Enter stride value: 2

Input Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Generated Strided Matrix:
[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]

Moving Averages:
[ 1.5  3.5  5.5  7.5  9.5 11.5]
